version: "3.7"

services:
  database:
    image: mysql:8.3
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: SommelAI
      MYSQL_USER: SommelAI
      MYSQL_PASSWORD: SommelAI2025!!!
    ports:
      - "3336:3306"
